#!/usr/bin/with-contenv bash
set -e
# shellcheck shell=bash

cat > /tmp/ombi-ingress-nginx.conf <<'NGINX'
events {}

http {
    server {
        listen 3579 default_server;

        allow 172.30.32.2;
        allow 127.0.0.1;
        deny all;

        proxy_buffering off;
        proxy_request_buffering off;
        proxy_http_version 1.1;

        location / {
            proxy_pass http://127.0.0.1:3578;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Prefix $http_x_ingress_path;
            proxy_set_header X-Ingress-Path $http_x_ingress_path;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_redirect ~^(/.*)$ $http_x_ingress_path$1;
        }
    }
}
NGINX

exec nginx -c /tmp/ombi-ingress-nginx.conf -g 'daemon off;'
